[package]
name = "babyrs"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version = "0.4.24", features = ["serde"]}
csv = "1.2.1"
diesel = { version = "2.0.4", features = ["sqlite", "chrono", "r2d2"] }
diesel_migrations = "2.0.0"
dotenvy = "0.15.7"
lazy_static = "1.4.0"
log = "0.4.17"
serde = "1.0.160"
simple_logger = "4.1.0"
