-- Your SQL goes here
CREATE TABLE events (
    id INTEGER NOT NULL PRIMARY KEY,
    dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP UNIQUE,
    urine BOOLEAN NOT NULL DEFAULT FALSE,
    stool BOOLEAN NOT NULL DEFAULT FALSE,
    skin2skin INTEGER NOT NULL DEFAULT 0,
    breastfeed INTEGER NOT NULL DEFAULT 0,
    breastmilk INTEGER NOT NULL DEFAULT 0,
    formula INTEGER NOT NULL DEFAULT 0,
    pump INTEGER NOT NULL DEFAULT 0
)
